# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_h2_kernel <- function(X, hp, kt) {
    .Call(`_schnellerGP_create_h2_kernel`, X, hp, kt)
}

solve_h2_vector <- function(gp, d_precond, X, tolerance) {
    .Call(`_schnellerGP_solve_h2_vector`, gp, d_precond, X, tolerance)
}

solve_h2_vector_start <- function(gp, d_precond, X, start, tolerance) {
    .Call(`_schnellerGP_solve_h2_vector_start`, gp, d_precond, X, start, tolerance)
}

add_diag <- function(gp, dv) {
    invisible(.Call(`_schnellerGP_add_diag`, gp, dv))
}

multiply_h2_vector <- function(gp, dv) {
    .Call(`_schnellerGP_multiply_h2_vector`, gp, dv)
}

multiply_h2_stdnorm <- function(gp) {
    .Call(`_schnellerGP_multiply_h2_stdnorm`, gp)
}

convert_h2_to_h_matrix <- function(gp) {
    .Call(`_schnellerGP_convert_h2_to_h_matrix`, gp)
}

save_h2_matrix <- function(file, gp) {
    invisible(.Call(`_schnellerGP_save_h2_matrix`, file, gp))
}

get_h2_idx <- function(gp) {
    .Call(`_schnellerGP_get_h2_idx`, gp)
}

cholesky_hmatrix <- function(gp) {
    invisible(.Call(`_schnellerGP_cholesky_hmatrix`, gp))
}

solve_hmatrix <- function(gp, x) {
    .Call(`_schnellerGP_solve_hmatrix`, gp, x)
}

log_sqrt_determinant_hmatrix <- function(gp) {
    .Call(`_schnellerGP_log_sqrt_determinant_hmatrix`, gp)
}

save_h_matrix <- function(file, gp) {
    invisible(.Call(`_schnellerGP_save_h_matrix`, file, gp))
}

read_h_matrix <- function(file) {
    .Call(`_schnellerGP_read_h_matrix`, file)
}

multiply_hmat_vec <- function(h, v) {
    .Call(`_schnellerGP_multiply_hmat_vec`, h, v)
}

get_n_levels <- function(N, M) {
    .Call(`_schnellerGP_get_n_levels`, N, M)
}

setup_compressedMatrixGP_MaternP1 <- function(X, sigma, rho, tol, M) {
    .Call(`_schnellerGP_setup_compressedMatrixGP_MaternP1`, X, sigma, rho, tol, M)
}

setup_compressedMatrixGP_sqrExp <- function(X, sigma, rho, tol, M) {
    .Call(`_schnellerGP_setup_compressedMatrixGP_sqrExp`, X, sigma, rho, tol, M)
}

setup_compressedMatrixGP_sqrExpP1 <- function(X, sigma, rho, tol, M) {
    .Call(`_schnellerGP_setup_compressedMatrixGP_sqrExpP1`, X, sigma, rho, tol, M)
}

setup_compressedMatrixGP_Matern <- function(X, sigma, rho, tol, M) {
    .Call(`_schnellerGP_setup_compressedMatrixGP_Matern`, X, sigma, rho, tol, M)
}

setup_compressedMatrixGP_Matern_tP <- function(X, tP, sigma, rho, tol, M) {
    .Call(`_schnellerGP_setup_compressedMatrixGP_Matern_tP`, X, tP, sigma, rho, tol, M)
}

simulate_compressedMatrixGP_TP <- function(N, GPobj, tP) {
    .Call(`_schnellerGP_simulate_compressedMatrixGP_TP`, N, GPobj, tP)
}

simulate_compressedMatrixGP <- function(N, GPobj) {
    .Call(`_schnellerGP_simulate_compressedMatrixGP`, N, GPobj)
}

getSymmetricFactor <- function(GPobj) {
    .Call(`_schnellerGP_getSymmetricFactor`, GPobj)
}

matmatProduct <- function(GPobj, M) {
    .Call(`_schnellerGP_matmatProduct`, GPobj, M)
}

solve_HODLR <- function(GPobj, b) {
    .Call(`_schnellerGP_solve_HODLR`, GPobj, b)
}

